# coding: utf-8

"""
    Schema API - OpenAPI 3.1

    This is a Schema extraction API based on the OpenAPI 3.1 specification.  You can find out more about Swagger at [https://swagger.io](https://swagger.io). 

    The version of the OpenAPI document: 0.8.0
    Contact: philipp.schmurr@kit.edu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from simpler_model.models.data_source_text_data_inner import DataSourceTextDataInner
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DataSource(BaseModel):
    """
    DataSource
    """ # noqa: E501
    id: StrictStr
    plugin: StrictStr
    description: Optional[StrictStr] = None
    populated_input_fields: Optional[List[StrictStr]] = None
    text_data: Optional[List[DataSourceTextDataInner]] = None
    __properties: ClassVar[List[str]] = ["id", "plugin", "description", "populated_input_fields", "text_data"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DataSource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in text_data (list)
        _items = []
        if self.text_data:
            for _item in self.text_data:
                if _item:
                    _items.append(_item.to_dict())
            _dict['text_data'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DataSource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in DataSource) in the input: " + _key)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "plugin": obj.get("plugin"),
            "description": obj.get("description"),
            "populated_input_fields": obj.get("populated_input_fields"),
            "text_data": [DataSourceTextDataInner.from_dict(_item) for _item in obj.get("text_data")] if obj.get("text_data") is not None else None
        })
        return _obj


