# coding: utf-8

"""
    Schema API - OpenAPI 3.1

    This is a Schema extraction API based on the OpenAPI 3.1 specification.  You can find out more about Swagger at [https://swagger.io](https://swagger.io). 

    The version of the OpenAPI document: 0.8.0
    Contact: philipp.schmurr@kit.edu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401



from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from simpler_model.models.assign_ontology_term_operation import AssignOntologyTermOperation
from simpler_model.models.convert_attribute_to_relation_operation import ConvertAttributeToRelationOperation
from simpler_model.models.rename_attribute_operation import RenameAttributeOperation
from typing import Union, Any, List, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal
from pydantic import StrictStr, Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

ENHANCEMENTOPERATION_ONE_OF_SCHEMAS = ["AssignOntologyTermOperation", "ConvertAttributeToRelationOperation", "RenameAttributeOperation"]

class EnhancementOperation(BaseModel):
    """
    EnhancementOperation
    """
    # data type: RenameAttributeOperation
    oneof_schema_1_validator: Optional[RenameAttributeOperation] = None
    # data type: ConvertAttributeToRelationOperation
    oneof_schema_2_validator: Optional[ConvertAttributeToRelationOperation] = None
    # data type: AssignOntologyTermOperation
    oneof_schema_3_validator: Optional[AssignOntologyTermOperation] = None
    actual_instance: Optional[Union[AssignOntologyTermOperation, ConvertAttributeToRelationOperation, RenameAttributeOperation]] = None
    one_of_schemas: List[str] = Literal["AssignOntologyTermOperation", "ConvertAttributeToRelationOperation", "RenameAttributeOperation"]

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = EnhancementOperation.model_construct()
        error_messages = []
        match = 0
        # validate data type: RenameAttributeOperation
        if not isinstance(v, RenameAttributeOperation):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RenameAttributeOperation`")
        else:
            match += 1
        # validate data type: ConvertAttributeToRelationOperation
        if not isinstance(v, ConvertAttributeToRelationOperation):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ConvertAttributeToRelationOperation`")
        else:
            match += 1
        # validate data type: AssignOntologyTermOperation
        if not isinstance(v, AssignOntologyTermOperation):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AssignOntologyTermOperation`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in EnhancementOperation with oneOf schemas: AssignOntologyTermOperation, ConvertAttributeToRelationOperation, RenameAttributeOperation. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in EnhancementOperation with oneOf schemas: AssignOntologyTermOperation, ConvertAttributeToRelationOperation, RenameAttributeOperation. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into RenameAttributeOperation
        try:
            instance.actual_instance = RenameAttributeOperation.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ConvertAttributeToRelationOperation
        try:
            instance.actual_instance = ConvertAttributeToRelationOperation.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AssignOntologyTermOperation
        try:
            instance.actual_instance = AssignOntologyTermOperation.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into EnhancementOperation with oneOf schemas: AssignOntologyTermOperation, ConvertAttributeToRelationOperation, RenameAttributeOperation. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into EnhancementOperation with oneOf schemas: AssignOntologyTermOperation, ConvertAttributeToRelationOperation, RenameAttributeOperation. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        to_dict = getattr(self.actual_instance, "to_dict", None)
        if callable(to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


