templateDir: /local/custom-openapi-template/python-fastapi-external-model
# the ignore list is theoretically only necessary for the first generation - afterwards it is best to just edit the ignore file that has been added to git
#openapiGeneratorIgnoreList:
#  - setup.cfg
#  - requirements.txt
#   # - .openapi-generator-ignore  # specifiying this here does not really make sense since the file is written anyway when we use openapiGeneratorIgnoreList
#  - src/simpler_model/models/extra_models.py

# ignoreFileOverride: generate-python-api-ignore  # for some reason this does not work at the moment - I think I had it working with an older version though

# globalProperties:
  # apis: ""
  # supportingFiles: ""
  # debugModels: true

# modelPackage: simpler_model  # this is concated with the packageName inside the generator java code and therefore useless for our purpose
# customModelPackge: simpler_model  # this does not work - but putting it into additionalProperties works

inputSpec: /local/spec/0/openapi3_1_merged.yaml
additionalProperties:
  allowUnicodeIdentifiers: false
  disallowAdditionalPropertiesIfNotPresent: false  # custom
  ensureUniqueParams: true
  enumUnknownDefaultCase: false
  fastapiImplementationPackage: simpler_api.impl  # custom
  legacyDiscriminatorBehavior: true
  packageName: simpler_api  # custom
  packageVersion: 0.1.0  # custom
  prependFormOrBodyParameters: false
  serverPort: 7373  # custom
  sortModelPropertiesByRequiredFlag: true
  sortParamsByRequiredFlag: true
  sourceFolder: src
  customModelPackage: simpler_model.models
# languageSpecificPrimitives:
#   - ModelSchema
#   - Attribute
#   - Entity
#   - EntityLink
#   - EntityKey
#   - Key
files:
#   models__init__.mustache:

  package__init__.mustache:
    folder: src/simpler_api
    destinationFilename: __init__.py
