templateDir: /local/custom-openapi-template/python-model-only
# the ignore list is theoretically only necessary for the first generation - afterwards it is best to just edit the ignore file that has been added to git
#openapiGeneratorIgnoreList:
#  - setup.cfg
#  - requirements.txt
#  - Dockerfile
#  - docker-compose.yaml
#  - src/simpler_model/main.py
#  - src/simpler_model/security_api.py
#  - src/simpler_model/impl/*
#  - src/simpler_model/apis/*
#  - src/simpler_model/models/extra_models.py
globalProperties:
  models: ""
  supportingFiles: ""
inputSpec: /local/spec/0/openapi3_1_merged.yaml
additionalProperties:
  allowUnicodeIdentifiers: false
  disallowAdditionalPropertiesIfNotPresent: false  # custom
  ensureUniqueParams: true
  enumUnknownDefaultCase: false
  fastapiImplementationPackage: simpler_model.impl  # custom
  legacyDiscriminatorBehavior: true
  packageName: simpler_model  # custom
  packageVersion: 0.1.0  # custom
  prependFormOrBodyParameters: false
  serverPort: 7373  # custom
  sortModelPropertiesByRequiredFlag: true
  sortParamsByRequiredFlag: true
  sourceFolder: src
files:
  package__init__.mustache:
    folder: src/simpler_model
    destinationFilename: __init__.py
