# coding: utf-8

"""
    Schema API - OpenAPI 3.1

    This is a Schema extraction API based on the OpenAPI 3.1 specification.  You can find out more about Swagger at [https://swagger.io](https://swagger.io). 

    The version of the OpenAPI document: 0.8.0
    Contact: philipp.schmurr@kit.edu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI
try:
    from simpler_api.impl.preload import on_app_created
except ImportError:
    def on_app_created(x): return

from simpler_api.apis.correction_api import router as CorrectionApiRouter
from simpler_api.apis.data_source_api import router as DataSourceApiRouter
from simpler_api.apis.enhancement_api import router as EnhancementApiRouter
from simpler_api.apis.entity_api import router as EntityApiRouter
from simpler_api.apis.format_api import router as FormatApiRouter
from simpler_api.apis.identifier_api import router as IdentifierApiRouter
from simpler_api.apis.partition_api import router as PartitionApiRouter
from simpler_api.apis.raw_api import router as RawApiRouter
from simpler_api.apis.schema_api import router as SchemaApiRouter
from simpler_api.apis.semantics_api import router as SemanticsApiRouter

app = FastAPI(
    title="Schema API - OpenAPI 3.1",
    description="This is a Schema extraction API based on the OpenAPI 3.1 specification.  You can find out more about Swagger at [https://swagger.io](https://swagger.io). ",
    version="0.8.0",
)

app.include_router(CorrectionApiRouter)
app.include_router(DataSourceApiRouter)
app.include_router(EnhancementApiRouter)
app.include_router(EntityApiRouter)
app.include_router(FormatApiRouter)
app.include_router(IdentifierApiRouter)
app.include_router(PartitionApiRouter)
app.include_router(RawApiRouter)
app.include_router(SchemaApiRouter)
app.include_router(SemanticsApiRouter)

on_app_created(app)
