name: Build Python Packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      # it seems fetch-tags is bugged (generally or just with on/push/tags)
      # https://github.com/actions/checkout/issues/1467
      # with:
      #   fetch-tags: true
    - name: Workaround to have tags available
      run: git fetch -f --tags

    - name: Collect relevant tags
      id: collect_tags
      run: |
        tags=""
        while read -r line; do
          if git describe --exact-match --match "$line" >/dev/null 2>&1; then
            tags+="$line "
          fi
        done < <(git tag -l | sed -E 's/[0-9]+\.[0-9]+\.[0-9]+/*/g' | sort | uniq)
        echo "::set-output name=TAGS::$tags"

    - name: Check if TAGS is empty
      run: |
        if [ -z "${{ steps.collect_tags.outputs.TAGS }}" ]; then
          echo "No tags on current main branch commit found. Stopping workflow."
          exit 1
        fi

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build model package
      if: contains(steps.collect_tags.outputs.TAGS, 'model-*')
      # if: startsWith(github.ref, 'refs/tags/model-')
      run: python -m build simpler-model/.

    - name: Build core package
      if: contains(steps.collect_tags.outputs.TAGS, 'core-*')
      # if: startsWith(github.ref, 'refs/tags/core-')
      run: python -m build simpler-core/.

    - name: Build cli package
      if: contains(steps.collect_tags.outputs.TAGS, 'cli-*')
      # if: startsWith(github.ref, 'refs/tags/cli-')
      run: python -m build simpler-cli/.

    - name: Build api package
      if: contains(steps.collect_tags.outputs.TAGS, 'api-*')
      # if: startsWith(github.ref, 'refs/tags/api-')
      run: python -m build simpler-core/.

    - name: Build plugin-json package
      if: contains(steps.collect_tags.outputs.TAGS, 'plugin-json-*')
      # if: startsWith(github.ref, 'refs/tags/plugin-json-')
      run: python -m build simpler-plugin-json/.

    - name: Build plugin-rdf package
      if: contains(steps.collect_tags.outputs.TAGS, 'plugin-rdf-*')
      # if: startsWith(github.ref, 'refs/tags/plugin-rdf-')
      run: python -m build simpler-plugin-rdf/.
      
    - name: Build plugin-sql package
      if: contains(steps.collect_tags.outputs.TAGS, 'plugin-sql-*')
      # if: startsWith(github.ref, 'refs/tags/plugin-sql-')
      run: python -m build simpler-plugin-sql/.
    
    - name: Build plugin-tabular package
      if: contains(steps.collect_tags.outputs.TAGS, 'plugin-tabular-*')
      # if: startsWith(github.ref, 'refs/tags/plugin-tabular-')
      run: python -m build simpler-plugin-tabular/.

    - name: Build plugin-xml package
      if: contains(steps.collect_tags.outputs.TAGS, 'plugin-xml-*')
      # if: startsWith(github.ref, 'refs/tags/plugin-xml-')
      run: python -m build simpler-plugin-xml/.

    - name: Publish package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload */dist/*
      