name: Build Python Packages

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      # it seems fetch-tags is bugged (generally or just with on/push/tags)
      # https://github.com/actions/checkout/issues/1467
      # with:
      #   fetch-tags: true
    - name: Workaround to have tags available
      run: git fetch -f --tags

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build model package
      if: startsWith(github.ref, 'refs/tags/model-')
      run: python -m build simpler-model/.

    - name: Build core package
      if: startsWith(github.ref, 'refs/tags/core-')
      run: python -m build simpler-core/.

    - name: Build cli package
      if: startsWith(github.ref, 'refs/tags/cli-')
      run: python -m build simpler-cli/.

    - name: Build api package
      if: startsWith(github.ref, 'refs/tags/api-')
      run: python -m build simpler-core/.

    - name: Build plugin-json package
      if: startsWith(github.ref, 'refs/tags/plugin-json-')
      run: python -m build simpler-plugin-json/.

    - name: Build plugin-rdf package
      if: startsWith(github.ref, 'refs/tags/plugin-rdf-')
      run: python -m build simpler-plugin-rdf/.
      
    - name: Build plugin-sql package
      if: startsWith(github.ref, 'refs/tags/plugin-sql-')
      run: python -m build simpler-plugin-sql/.
    
    - name: Build plugin-tabular package
      if: startsWith(github.ref, 'refs/tags/plugin-tabular-')
      run: python -m build simpler-plugin-tabular/.

    - name: Build plugin-xml package
      if: startsWith(github.ref, 'refs/tags/plugin-xml-')
      run: python -m build simpler-plugin-xml/.

    - name: Publish package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload */dist/*
      